### ISSUE TITLE
setFunctionAsString

### ISSUE THREAD

**Issue by marciodel** [highcharts4gwt/highcharts#1]
It seens that the parameter being used in the functions is not used correctly. In the declaration it is functionAsString but in the JSNI it is using valueToBeEvaluated

**Comment by ronanquillevere** [comment]
Thanks for reporting this I will correct this asap

**Comment by ronanquillevere** [comment]
Ok due to the latest changes done by highcharts in their api I need some heavy modifications to my code.

Do not know when everything will be fixed.

**Comment by ronanquillevere** [comment]
FIxed 265850dbdc46c22eb07ad6fd088e839d234726ff
